### ISSUE TITLE
how to install in anaconda environment?

### ISSUE THREAD

**Issue by chenchr** [szagoruyko/pyinn#8]
hello, I do the follow instruction:
pip install git+https://github.com/szagoruyko/pyinn.git@master
Them in python, the code:
```
import torch
from torch.autograd import Variable
import pyinn as P
x = Variable(torch.randn(1,4,5,5).cuda())
w = Variable(torch.randn(4,1,3,3).cuda())
y = P.conv2d_depthwise(x, w, padding=1)
```
However, a error occurs:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-9e6423fc5d6b> in <module>()
      7 import torch
      8 from torch.autograd import Variable
----> 9 import pyinn as P
     10 x = Variable(torch.randn(1,4,5,5).cuda())
     11 w = Variable(torch.randn(4,1,3,3).cuda())

/home/chenchr/anaconda3/lib/python3.6/site-packages/pyinn/__init__.py in <module>()
----> 1 from ncrelu import ncrelu
      2 from dgmm import dgmm
      3 from cdgmm import cdgmm
      4 from im2col import im2col, col2im
      5 from conv2d_depthwise import conv2d_depthwise

ModuleNotFoundError: No module named 'ncrelu'

I've install pytorch by conda install.

**Comment by szagoruyko** [comment]
hm I think this should be py2/py3 differences, let me check

**Comment by szagoruyko** [comment]
@chenchr please reinstall pyinn, should be fixed now

**Comment by chenchr** [comment]
@szagoruyko yes. With the module path prefixed by a dot it work.Thanks.
